scdhhs/ui-components

src/ValueChangeMixin.js
test/unit/value-change-mixin-spec.js

RMMIS-5101 - Allow configuration of the FIELD_VALUE_CHANGE action and wrote test for ValueChangeMixin.js

RMMIS-5101-allow-config-of-field-value-change

---

package.json
src/AutoComplete.jsx
src/EntryList.jsx
src/Factory.jsx
src/Grid.jsx
src/Workflow.jsx
test/fixtures/workflow-simple.json
test/unit/editor-toggle-spec.js
test/unit/field-value-mixin-spec.js
test/unit/main-spec.js
test/unit/utils-spec.js
test/unit/value-change-mixin-spec.js
test/unit/workflow-spec.js

ALLTHEWARNINGS(except three that are necessary)

Fix warnings

---

src/EntryList.jsx
src/EntryListItem.jsx
src/constants.js
src/styles/EntryList.less
test/fixtures/entrylist-config.json
test/unit/entrylist-spec.js

RMMIS-5122: Add ability to edit entries in EntryList component - Take 2! :8ball:

RMMIS-5122-edit-entry-list

---

src/EntryList.jsx
src/EntryListAddBtn.jsx
src/EntryListBtn.jsx

RMMIS-5480: Hide EntryList add entry button if the form is showing

RMMIS-5480-hide-entry-list-add-btn

---

src/EntryList.jsx
src/constants.js

RMMIS-5481: Cancel button that removes form and resets the entry object

RMMIS-5481: entry-list-cancel-btn

---

src/Date.jsx
test/unit/date-spec.js

RMMIS-5497: Add support for the react-widget time picker to the Date component

RMMIS-5497-add-time-support-to-date-component

---

src/Date.jsx

RMMIS-5503: Pass in input props for visible and disabled for Date component

RMMIS-5503-allow-date-to-get-disabled-visible

---

src/FieldGroup.jsx
test/unit/field-group-spec.js

RMMIS-5503: Allow use of custom fieldValueChangeAction in FieldGroup component

RMMIS-5503-field-group-custom-fvc

---

src/Workflow.jsx
src/WorkflowItem.jsx
test/fixtures/workflow-with-children.json
test/unit/workflow-item-editor-toggle-spec.js
test/unit/workflow-spec.js

RMMIS-5686: Create top level category pages that can be skipped since they are not real pages.

rmmis-5686 top level category for non pages

---

src/inputMaskUtils.js

RMMIS-5738: Fixed maskUtils not filtering out separators for pasted values, corrected a typo

RMMIS-5738-mask-filter-pasted-value

---

src/EntryList.jsx
src/EntryListItem.jsx

RMMIS-5610: Added Actions table header text on EntryList, misc cleanup and ES6ification

RMMIS-5610-medicaid-entrylist-missing-header

---

src/Input.jsx
test/unit/input-spec.js

RMMIS-6074: Added support for masking default input values & wrote test for that functionality

RMMIS-6074-mask-default-input-values

---

src/Terms.jsx
src/styles/Terms.less
src/styles/index.less

RMMIS-6076: Replaced containing div element with a fieldset and made a form-group, added an optional legend and checkbox header

RMMIS-6076-terms-updates

---

src/Date.jsx
test/unit/date-spec.js

RMMIS-6076: Allow the user to choose to prepopulate a Date component's value with today's date.

RMMIS-6076-todays-date

---

src/Field.jsx
src/utils.js
test/fixtures/field-prepopulate-concat.json
test/fixtures/field-prepopulate-visibility.json
test/unit/field-spec.js
test/unit/utils-spec.js

RMMIS-5820: Wrote the logic to pre-populate field values from previous page values and/or perform operations on them, wrote tests for both the Field component & the utils, ES6ified ALLTHETHINGS

RMMIS-5820-pre-populate-fields

---

src/utils.js
test/unit/utils-spec.js

Add Support for formatting Dates in 'mm/dd/yyyy' format from time stamp stored in the Application

RMMIS-6337-support-formatting-dates-on-review-and-submit

---

src/Terms.jsx

RMMIS-6338: Bring Terms component up to snuff with the single-checkbox practices for good measure.

RMMIS-6338-terms-component-persist-attested-value

---

src/Date.jsx
src/ValueChangeMixin.js

RMMIS-6345 - Added support for persisting today’s date in the application

RMMIS-6345-support-for-persisting-todays-date

---

src/Date.jsx
src/utils.js
test/unit/date-spec.js
test/unit/options-mixin-spec.js

Fixed an issue where Date field would clear out any entered value after validation. Also cleaned up the utils#getDateString method, some tests.

Date component validation fix

---

src/Field.jsx

RMMIS-6502: Fixed issue with initial character input being removed before passed as props

RMMIS-6502-max-slicing-issue

---

package.json
src/Grid.jsx
test/unit/grid-layout-spec.js

fix issue where grid column was not passing the schema to its child components

update classnames dependency to v2,

---

src/Date.jsx
src/Field.jsx
test/fixtures/field-date.json
test/unit/date-spec.js

RMMIS-6514: Fixed Date component, allow more than the standard input props for Date, updated tests to support latest changes

RMMIS-6514-fix-date-component

---

src/EntryList.jsx
src/File.jsx
test/unit/file-spec.js

RMMIS-6516: Changes to File & EntryList to support CRUD and the file API in UIC 3

RMMIS-6516: Support file API in UIC 3

---

src/Accordion.jsx
src/AccordionPanel.jsx
src/File.jsx
src/styles/Button.less
src/styles/index.less
test/unit/accordion-spec.js

RMMIS-6637: Changes to UIC to support the new Accordion/AccordionPanel and File functionality for the Page Summary component and in general.

RMMIS-6637-review-and-submit

---

src/Terms.jsx

RMMIS-6908: Added an onChange handler in the Terms component and update the child checkbox component's value accordingly

RMMIS-6908: fix-terms-component
